[package]
name = "speck"
version = "0.1.0"
authors = ["Markus Ã…kesson <macke.95_06@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
